

stages:
  - test 


start-tests:
  stage: test
  script:
    - echo "Starting testing... This can take some time"


test-admin-access:
  variables:
    DOCKER_DRIVER: overlay


  image: docker:latest
  stage: test  
  services:
    - docker:dind
  tags:
    - docker
    - linux
  before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install docker-compose

    - docker-compose --profile backend up --detach &
  script:
    - echo "Testing admin access..."
    - cd specification-tests
    - chmod +x ./run.sh
    - ./run.sh -d . admin-any

  after_script:
    - docker-compose --profile backend down

 

