stages:
  - test 


start-tests:
  stage: test
  script:
    - echo "Starting testing... This can take some time"


test-admin-access:
  stage: test  
  image: docker:latest

  services:
    - docker:dind

  before_script:
    - apk add --no-cache --upgrade bash
    - docker info
    - apk update
    - apk upgrade
    - apk add python3 py3-pip build-base
    - docker-compose --profile backend create
    - docker-compose --profile backend start --detach &
    - pip install docker-compose
    - apk add --update curl && rm -rf /var/cache/apk/*
    - bash wait-for-container.sh architecture-css0-1
    - bash wait-for-container.sh architecture-css2-1
    - bash wait-for-container.sh architecture-css3-1
    - bash wait-for-container.sh architecture-css4-1
    - echo "127.0.0.1       server" >> /etc/hosts
    - cat /etc/hosts
  script:
    - echo "Testing admin access..."
    - cd specification-tests
    - pwd
    - chmod +x ./run.sh
    - bash run.sh -d . admin-any

  after_script:
    - docker-compose --profile backend down

 