stages:
  - test 

start-tests:
  stage: test
  script:
    - echo "Starting testing... This can take some time"


test-admin-access:
  stage: test  
  image: docker:latest

  services:
    - docker:dind

  before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add --no-cache --upgrade bash
    - apk add python3 py3-pip build-base
    - pip install docker-compose
    - sh -c bash
    - apk add --update nodejs npm
    - npm install --global yarn
    - apk add --update openjdk11
    - apk add openssl
    - yarn install
    - yarn run setup
    - yarn run dt:mapping:pipeline 
    - cd scripts/cert
    - chmod +x main.sh
    - bash main.sh
    - cd ../../
    - docker-compose --profile backend --profile test up --wait
    - sleep 10 
    - bash wait-for-container.sh architecture-bashlib-1
  script:
    - echo "Testing admin access..."
    - curl --insecure https://css-test
    - curl --insecure https://css0
    - curl --insecure https://css1
    - curl --insecure https://css2
    - cd specification-tests
    - chmod +x ./run.sh
    - bash run.sh -d . admin-any

  after_script:
    - docker-compose --profile backend down

 