

stages:
  - test 


start-tests:
  stage: test
  script:
    - echo "Starting testing... This can take some time"


test-admin-access:
  stage: test  
  before_script:
    - docker-compose --profile backend up &
  script:
    - echo "Testing admin access..."
    - cd specification-tests
    - ./run.sh -d . admin-any
    - docker-compose --profile backend down

 

