

stages:
  - test 


start-tests:
  stage: test
  script:
    - echo "Starting testing... This can take some time"


test-admin-access:
  stage: test  

  tags:
    - docker
    - linux
  before_script:
    - docker compose --profile backend up --detach &
  script:
    - echo "Testing admin access..."
    - cd specification-tests
    - chmod +x ./run.sh
    - ./run.sh -d . admin-any

  after_script:
    - docker compose --profile backend down

 

