services:
  ##############################################################################
  # PODS
  ##############################################################################
  css0:
    profiles: [ "pod"]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3081:80"
      - "4081:443"
      
    environment:
      - CSS_BASE_URL=https://css0
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/user1
        target: /pods/user1
      - type: bind
        source: ./actors/user1/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css0:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro


  ##############################################################################
  # FRONTEND
  ##############################################################################
  webclient:
    profiles: [ "frontend"]
    image: comunica/jquery-widget.js:latest
    ports:
      - 443:443
    volumes:
      - ./actors/webclient/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./scripts/cert/outputs/webclient:/etc/ssl/cert:ro
  
  browser:
    profiles: [ "frontend" ]
    image: jlesage/firefox:latest
    shm_size: '2g'
    environment:
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - FF_OPEN_URL=https://webclient
    ports:
      - 5800:5800
    volumes:
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
      - ./volumes/browser-data:/config:rw