services:
  ##############################################################################
  # PODS
  ##############################################################################
  css0:
    profiles: [ "pod", "backend" ]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3081:80"
      - "4081:443"
      
    environment:
      - CSS_BASE_URL=https://css0
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/admin
        target: /pods/admin
      - type: bind
        source: ./actors/admin/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css0:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate https://css0 --spider; then touch healthy.flag; else false; fi"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  css1:
    profiles: [ "pod", "backend" ]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3082:80"
      - "4082:443" 
    environment:
      - CSS_BASE_URL=https://css1
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/lindner-group
        target: /pods/lindner-group
      - type: bind
        source: ./actors/lindner-group/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css1:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate https://css1 --spider; then touch healthy.flag; else false; fi"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  css2:
    profiles: [ "pod", "backend" ]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3083:80"
      - "4083:443" 
    environment:
      - CSS_BASE_URL=https://css2
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/building-owner
        target: /pods/building-owner
      - type: bind
        source: ./actors/building-owner/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css2:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate https://css2 --spider; then touch healthy.flag; else false; fi"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s      

  css3:
    profiles: [ "pod", "backend" ]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3084:80"
      - "4084:443" 
    environment:
      - CSS_BASE_URL=https://css3
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/building-owner2
        target: /pods/building-owner2
      - type: bind
        source: ./actors/building-owner2/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css3:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate https://css3 --spider; then touch healthy.flag; else false; fi"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  css4:
    profiles: [ "pod", "backend" ]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3085:80"
      - "4085:443" 
    environment:
      - CSS_BASE_URL=https://css4
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/ragn-sells
        target: /pods/ragn-sells
      - type: bind
        source: ./actors/ragn-sells/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css4:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate https://css4 --spider; then touch healthy.flag; else false; fi"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s    

  ##############################################################################
  # FRONTEND
  ##############################################################################
  webclient:
    profiles: [ "frontend"]
    image: comunica/jquery-widget.js:latest
    ports:
      - 443:443
    volumes:
      - ./actors/webclient/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./scripts/comunica/outputs/queries.json:/usr/share/nginx/html/queries.json
      - ./scripts/cert/outputs/webclient:/etc/ssl/cert:ro
  
  browser:
    profiles: [ "frontend" ]
    image: jlesage/firefox:latest
    shm_size: '2g'
    environment:
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - FF_OPEN_URL=https://webclient
    ports:
      - 5800:5800
    volumes:
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
      - ./volumes/browser-data:/config:rw
      - ./scripts/cert/outputs/certificate-authority:/config/Desktop:rw
  
  ##############################################################################
  # 
  ##############################################################################
  bashlib:
    profiles: [ "backend" ]
    build: ./bashlib-build
    environment:
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
      - ./scripts/ac:/scripts:rw
    depends_on:
      css1:
        condition: service_healthy
      css2:
        condition: service_healthy
      css3:
        condition: service_healthy
      css4:
        condition: service_healthy
    stdin_open: true
    tty: true
    
  ##############################################################################
  # TESTING 
  ##############################################################################
  css-test:
    profiles: [ "test" ]
    image: gddmulde/community-solid-server:latest
    ports:
      - "3086:80"
      - "4086:443" 
    environment:
      - CSS_BASE_URL=https://css-test
      - CSS_CONFIG=/config/server.json
      - CSS_ROOT_FILE_PATH=/pods
      - CSS_SEEDED_POD_CONFIG_JSON=/config/pods.json
      - CSS_PORT=443
      - CSS_HTTPS_KEY=/my-cert/actor-private.key
      - CSS_HTTPS_CERT=/my-cert/actor.crt
      - NODE_EXTRA_CA_CERTS=/shared-certs/ca.crt
    volumes:
      - type: bind
        source: ./actors/test
        target: /pods/test
      - type: bind
        source: ./actors/test/config/css-users.json
        target: /config/pods.json
      - type: bind
        source: ./common/css-01.json
        target: /config/server.json
      - type: bind
        source: ./common/templatepod
        target: /config/templatepod
      # these lines make the current computer's users and groups available in the container
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Certificates (todo: refactor cert resources from ./scripts to more appropriate location)
      - ./scripts/cert/outputs/css-test:/my-cert:ro
      - ./scripts/cert/outputs/certificate-authority:/shared-certs:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate https://css0 --spider; then touch healthy.flag; else false; fi"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
