# What are the materials of a given product?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX d: <https://www.example.com/data/>
PREFIX o: <https://www.example.com/ont/>

SELECT ?material ?name
WHERE {
  $product o:has-bom ?bom .
  ?bom o:has-bom-material-assoc ?assoc .
  ?assoc o:has-material ?material .
  OPTIONAL {
    ?material o:name ?name
  }
}
