# What are the tiles of a building with a given address?

PREFIX oo: <http://purl.org/openorg/>
PREFIX ao: <http://purl.org/ontology/ao/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX d: <https://www.example.com/data/>
PREFIX o: <https://www.example.com/ont/>

SELECT
	?tile
WHERE {
  ?b a o:Building ;
    o:address $address;
    o:has-floor-tile ?tile .
}
ORDER BY ?tile
