title: |md
# Open Circularity Platform - Public Docker based (with additional external Solid pod)
| { near: top-center }

vars: {
  private_address: "x.y.z.t"
}

browser: "User's Browser" {
  icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
  shape: image
}

www: "WWW" {
  shape: cloud
}

VW1: "imec ilabt environment" {
  public_ip: "Reverse proxy\nfrom public address to private address ${private_address}\nand from https to http" {
    icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FPublic%20IP%20Addresses.svg
    shape: image
  }
  node: "Ubuntu 24.04 LTS" {
    icon: https://icons.terrastruct.com/essentials%2F112-server.svg
    nginx: "" {
      icon: https://icons.terrastruct.com/dev%2Fnginx.svg
      shape: image
    }
    docker: "" {
      icon: https://icons.terrastruct.com/azure%2F_Companies%2FLogo-docker.svg
      css_0: css0 {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
      }
      css_i: cssi {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
      }
      css_n: cssN {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
      }
      gdv: "Generic Data Viewer" {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F089-data%20analysis.svg
      }
      qldf: "Comunica Webclient" {
        shape: image
        icon: https://query.linkeddatafragments.org/images/logo.svg
      }
    }

    nginx -> docker
  }

  public_ip -> node.nginx: "http://${private_address}/css0\nhttp://${private_address}/cssi\nhttp://${private_address}/cssn\nhttp://${private_address}/viewer\nhttp://${private_address}/webclient"
}
additional-server: "Any Solid server" {
  additional-pod: "Any additional Solid pod" {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F117-database.svg
  }
}

browser -- www
www -> VW1.public_ip: "https://onto-deside.ilabt.imec.be/*"
VW1.node.docker -> www: "https://onto-deside.ilabt.imec.be/css0\nhttps://onto-deside.ilabt.imec.be/cssi\nhttps://onto-deside.ilabt.imec.be/cssn\nhttps://onto-deside.ilabt.imec.be/viewer\nhttps://onto-deside.ilabt.imec.be/webclient\nhttps://some-solid-pod.example.com"
www --> additional-server.additional-pod: "https://some-solid-pod.example.com"
