title: |md
# Open Circularity Platform - Development and stand-alone demo
| { near: top-center }

host: "Host computer" {
  icon: https://icons.terrastruct.com/tech%2Fdesktop.svg

  browser: "User's Browser" {
    icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
    shape: image
  }
  docker: "" {
    icon: https://icons.terrastruct.com/azure%2F_Companies%2FLogo-docker.svg
    css_0: css0 {
      shape: image
      icon: https://icons.terrastruct.com/essentials%2F117-database.svg
    }
    css_i: cssi {
      shape: image
      icon: https://icons.terrastruct.com/essentials%2F117-database.svg
    }
    css_n: cssN {
      shape: image
      icon: https://icons.terrastruct.com/essentials%2F117-database.svg
    }
    qldf: "Int. Comunica Webclient" {
      shape: image
      icon: https://query.linkeddatafragments.org/images/logo.svg
    }
    gdv: "Int. Generic Data Viewer" {
      shape: image
      icon: https://icons.terrastruct.com/essentials%2F089-data%20analysis.svg
    }
    docker_network: "Docker network" {
      shape: image
      icon: https://icons.terrastruct.com/infra%2F014-network.svg
    }
    ff: "Firefox container" {
      shape: image
      icon: https://icons.terrastruct.com/dev%2Ffirefox.svg
    }

    ff -- docker_network
    docker_network -- css_0: "https://css0.onto-deside.ilabt.imec.be"
    docker_network -- css_i: "https://cssi.onto-deside.ilabt.imec.be"
    docker_network -- css_n: "https://cssn.onto-deside.ilabt.imec.be"
    docker_network -- qldf: "https://webclient.onto-deside.ilabt.imec.be"
    docker_network -- gdv: "https://viewer.onto-deside.ilabt.imec.be"
  }

  browser -- docker.ff: "http://localhost:5800"
}
