# Query the actors
# Datasources: https://css1/lindner-group/profile/card#me https://css2/building-owner/profile/card#me https://css3/building-owner2/profile/card#me https://css4/ragn-sells/profile/card#me
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pim: <http://www.w3.org/ns/pim/space#>
PREFIX solid: <http://www.w3.org/ns/solid/terms#>

SELECT *
WHERE {
  ?agent
    a foaf:Agent;
    solid:oidcIssuer ?IDP;
    pim:storage ?storage;
  .
}
