subjects: /data/test-subjects.ttl
sources:
    - https://gitlab.ilabt.imec.be/KNoWS/projects/onto-deside/architecture/example2/web-access-control-test-manifest.ttl


mappings:
  - prefix: https://gitlab.ilabt.imec.be/KNoWS/projects/onto-deside/architecture
    path: /data
