PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bot: <https://w3id.org/bot#>

SELECT DISTINCT ?BuildingLabel
WHERE {
  ?Building a bot:Building ;
    rdfs:label ?BuildingLabel
}
ORDER BY ?BuildingLabel
