PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX textile:  <http://w3id.org/CEON/demo/textile/>
PREFIX elec: <http://w3id.org/CEON/demo/electronics/>
PREFIX ceon-product: <http://w3id.org/CEON/ontology/product/>
PREFIX ceon-resourceODP: <http://w3id.org/CEON/ontology/resourceODP/>

SELECT DISTINCT ?BatchLabel
WHERE {
  ?Batch a ceon-resourceODP:BatchOfObjects.
  ?Batch rdfs:label ?BatchLabel
}
ORDER BY ?BatchLabel
