PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX textile:  <http://w3id.org/CEON/demo/textile/>
PREFIX elec: <http://w3id.org/CEON/demo/electronics/>
PREFIX ceon-product: <http://w3id.org/CEON/ontology/product/>
PREFIX bot: <https://w3id.org/bot#>

SELECT DISTINCT ?ElementLabel
WHERE {
  ?Space bot:containsElement ?Element.
  ?Element rdfs:label ?ElementLabel
}
ORDER BY ?ElementLabel
