PREFIX schema: <http://schemaorg/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX ceon-actorODP: <http://w3id.org/CEON/ontology/actorODP/>
PREFIX ceon-resourceODP: <http://w3id.org/CEON/ontology/resourceODP/>
PREFIX ceon-product: <http://w3id.org/CEON/ontology/product/>
PREFIX ceon-provenance: <http://w3id.org/CEON/ontology/provenance/>
PREFIX ceon-material: <http://w3id.org/CEON/ontology/material/>
PREFIX ceon-processODP: <http://w3id.org/CEON/ontology/processODP/>
PREFIX ceon-process:  <http://w3id.org/CEON/ontology/process/>
PREFIX textile:  <http://w3id.org/CEON/demo/textile/>

SELECT DISTINCT ?Matter ?MassFraction
WHERE {
  ?Product rdfs:label $ProductLabel .
  ?Composition a ceon-product:MatterComposition;
  ceon-product:compositionOf ?Product;
  ceon-product:associatedWithMatter ?Matter_url;
  qudt:numericValue ?MassFraction.
  BIND (REPLACE(STR(?Matter_url), "^.*/([^/]*)$", "$1") as ?Matter)
}

